#!/usr/bin/env bash
# deploy.sh — Provision Document Intelligence + Azure OpenAI via Bicep
# Usage: bash infra/deploy.sh --resource-group <rg> --location <loc> [--what-if] [--yes]
set -euo pipefail

SCENARIO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INFRA_DIR="$SCENARIO_DIR/infra"

usage() {
  echo "Usage: $0 --resource-group <rg> --location <loc> [--what-if] [--yes]" >&2
  exit 1
}

RG=""
LOCATION=""
WHAT_IF=false
YES=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --resource-group) RG="$2"; shift 2 ;;
    --location)       LOCATION="$2"; shift 2 ;;
    --what-if)        WHAT_IF=true; shift ;;
    --yes)            YES=true; shift ;;
    *) usage ;;
  esac
done

[[ -z "$RG" || -z "$LOCATION" ]] && usage

# ── Login check ───────────────────────────────────────────────────────────────
az account show >/dev/null 2>&1 || { echo "[error] Not logged in. Run: az login"; exit 1; }
SUBSCRIPTION=$(az account show --query id -o tsv)
echo "[info] subscription: $SUBSCRIPTION"

# ── Provider registration ─────────────────────────────────────────────────────
echo "[info] registering Microsoft.CognitiveServices (idempotent)..."
az provider register --namespace Microsoft.CognitiveServices --wait

# ── Get deployer object ID ────────────────────────────────────────────────────
DEPLOYER_OBJECT_ID=$(az ad signed-in-user show --query id -o tsv 2>/dev/null || true)
if [[ -z "$DEPLOYER_OBJECT_ID" ]]; then
  echo "[warn] Could not detect signed-in user object ID (service principal?). Set manually." >&2
  DEPLOYER_OBJECT_ID="${DEPLOYER_OBJECT_ID:-<set-your-object-id>}"
fi
echo "[info] deployer objectId: $DEPLOYER_OBJECT_ID"

# ── Verify region availability (informational) ───────────────────────────────
echo "[info] checking region availability..."
az cognitiveservices account list-skus \
  --location "$LOCATION" --kind FormRecognizer --query "[?name=='S0']" -o table 2>/dev/null || \
  echo "[warn] could not verify DI S0 availability in $LOCATION"

# ── Resource group ────────────────────────────────────────────────────────────
az group create --name "$RG" --location "$LOCATION" --output none
echo "[info] resource group: $RG ($LOCATION)"

DEPLOY_NAME="arts02-$(date +%Y%m%d%H%M%S)"

# ── What-if / preflight ───────────────────────────────────────────────────────
if $WHAT_IF; then
  echo "[info] running --what-if (no changes will be made)..."
  az deployment group what-if \
    --resource-group "$RG" \
    --template-file "$INFRA_DIR/main.bicep" \
    --parameters "$INFRA_DIR/parameters.example.json" \
    --parameters deployerObjectId="$DEPLOYER_OBJECT_ID" location="$LOCATION"
  exit 0
fi

# ── Confirm ───────────────────────────────────────────────────────────────────
if ! $YES; then
  read -r -p "[confirm] Deploy to $RG in $LOCATION? [y/N] " ANS
  [[ "${ANS,,}" == "y" ]] || { echo "[aborted]"; exit 1; }
fi

# ── Deploy ────────────────────────────────────────────────────────────────────
echo "[info] deploying Bicep as '$DEPLOY_NAME'..."
OUTPUT=$(az deployment group create \
  --name "$DEPLOY_NAME" \
  --resource-group "$RG" \
  --template-file "$INFRA_DIR/main.bicep" \
  --parameters "$INFRA_DIR/parameters.example.json" \
  --parameters deployerObjectId="$DEPLOYER_OBJECT_ID" location="$LOCATION" \
  --query "properties.outputs" \
  --output json)

DI_ENDPOINT=$(echo "$OUTPUT"   | python3 -c "import json,sys; print(json.load(sys.stdin)['diEndpoint']['value'])")
AOAI_ENDPOINT=$(echo "$OUTPUT" | python3 -c "import json,sys; print(json.load(sys.stdin)['aoaiEndpoint']['value'])")
AOAI_DEPLOY=$(echo "$OUTPUT"   | python3 -c "import json,sys; print(json.load(sys.stdin)['aoaiDeploymentName']['value'])")

# ── Write .env (chmod 600) ────────────────────────────────────────────────────
ENV_FILE="$SCENARIO_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by infra/deploy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Authentication: DefaultAzureCredential (az login / Managed Identity / SP env vars)
AZURE_DOCINT_ENDPOINT=$DI_ENDPOINT
AZURE_OPENAI_ENDPOINT=$AOAI_ENDPOINT
AZURE_OPENAI_DEPLOYMENT=$AOAI_DEPLOY
AZURE_OPENAI_API_VERSION=2024-10-21
EOF
chmod 600 "$ENV_FILE"

echo "[done] .env written (chmod 600): $ENV_FILE"
echo "  DI endpoint:      $DI_ENDPOINT"
echo "  AOAI endpoint:    $AOAI_ENDPOINT"
echo "  AOAI deployment:  $AOAI_DEPLOY"
