#!/usr/bin/env bash
# deploy.sh — Idempotent deployment of Azure AI Speech resources for I-1.
# Usage: bash infra/deploy.sh [--what-if]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_DIR="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)/research-fields/arts-humanities/01-speech-transcription"

# ── Configuration (override via env or edit parameters.example.json) ──────────
RG="${AZURE_RESOURCE_GROUP:-rg-speech-quickstart}"
LOC="${AZURE_LOCATION:-japaneast}"
DEPLOYMENT_NAME="spread-speech-deploy"
PARAMS_FILE="$SCENARIO_DIR/infra/parameters.example.json"
TEMPLATE_FILE="$SCENARIO_DIR/infra/main.bicep"
ENV_FILE="$SCENARIO_DIR/.env"
WHAT_IF=0
[[ "${1:-}" == "--what-if" ]] && WHAT_IF=1

# ── Helpers ───────────────────────────────────────────────────────────────────
info()  { echo "[info]  $*"; }
warn()  { echo "[warn]  $*" >&2; }
error() { echo "[error] $*" >&2; exit 1; }

# ── 1. Verify az CLI ──────────────────────────────────────────────────────────
command -v az >/dev/null 2>&1 || error "Azure CLI (az) not found. Install: https://aka.ms/install-azure-cli"
AZ_VERSION=$(az version --query '"azure-cli"' -o tsv 2>/dev/null || echo "unknown")
info "az CLI version: $AZ_VERSION"

# ── 2. Verify login ───────────────────────────────────────────────────────────
ACCOUNT=$(az account show --query '{sub:id,name:name,user:user.name}' -o json 2>/dev/null) \
  || error "Not logged in. Run: az login"
SUB_ID=$(echo "$ACCOUNT" | grep -oP '"sub":\s*"\K[^"]+')
info "Subscription: $(echo "$ACCOUNT" | grep -oP '"name":\s*"\K[^"]+') ($SUB_ID)"

# ── 3. Install cognitiveservices extension (best-effort) ─────────────────────
az extension add -n cognitiveservices --upgrade --only-show-errors 2>/dev/null || true

# ── 4. Register provider ──────────────────────────────────────────────────────
info "Registering Microsoft.CognitiveServices provider..."
az provider register --namespace Microsoft.CognitiveServices --wait --only-show-errors

# ── 5. Verify Speech support in target region ─────────────────────────────────
info "Checking Speech availability in $LOC..."
SPEECH_AVAIL=$(az cognitiveservices account list-skus \
  --kind SpeechServices --location "$LOC" \
  --query "[?sku.name=='S0'] | length(@)" -o tsv 2>/dev/null || echo "0")
[[ "$SPEECH_AVAIL" -gt 0 ]] || error "SpeechServices S0 not available in region: $LOC"
info "SpeechServices S0 is available in $LOC."

# ── 6. Create resource group if missing ──────────────────────────────────────
if ! az group show -n "$RG" --only-show-errors &>/dev/null; then
  info "Creating resource group $RG in $LOC..."
  az group create -n "$RG" -l "$LOC" --only-show-errors -o none
else
  info "Resource group $RG already exists."
fi

# ── 7. Inject deployer principal into parameters ──────────────────────────────
DEPLOYER_OID=$(az ad signed-in-user show --query id -o tsv 2>/dev/null \
  || az account show --query 'user.name' -o tsv)
PRINCIPAL_TYPE="User"
# Detect service principal context
SP_TYPE=$(az account show --query 'user.type' -o tsv 2>/dev/null || echo "user")
[[ "$SP_TYPE" == "servicePrincipal" ]] && PRINCIPAL_TYPE="ServicePrincipal"

# Build a temporary parameters override (no secrets; only principal metadata)
PARAM_OVERRIDES="deployerObjectId=$DEPLOYER_OID deployerPrincipalType=$PRINCIPAL_TYPE"

# ── 8. Deploy (or what-if) ────────────────────────────────────────────────────
if [[ "$WHAT_IF" -eq 1 ]]; then
  info "Running what-if (no changes)..."
  az deployment group what-if \
    -g "$RG" \
    --name "$DEPLOYMENT_NAME" \
    --template-file "$TEMPLATE_FILE" \
    --parameters "@$PARAMS_FILE" $PARAM_OVERRIDES
  info "What-if complete. Re-run without --what-if to deploy."
  exit 0
fi

info "Deploying Bicep template (idempotent)..."
DEPLOY_OUT=$(az deployment group create \
  -g "$RG" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$TEMPLATE_FILE" \
  --parameters "@$PARAMS_FILE" $PARAM_OVERRIDES \
  --query 'properties.outputs' -o json)

SPEECH_RESOURCE=$(echo "$DEPLOY_OUT" | grep -oP '"speechResourceName".*?"value":\s*"\K[^"]+' || true)
SPEECH_REGION=$(echo "$DEPLOY_OUT"   | grep -oP '"speechRegion".*?"value":\s*"\K[^"]+'      || true)
SPEECH_ENDPOINT=$(echo "$DEPLOY_OUT" | grep -oP '"speechEndpoint".*?"value":\s*"\K[^"]+'    || true)

# ── 9. Write .env (no key — Entra auth preferred) ────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by infra/deploy.sh — $(date -Iseconds)
# Entra (DefaultAzureCredential) is the recommended auth method.
# Only set AZURE_SPEECH_KEY if you explicitly enable local auth (enableLocalAuth=true).
SPEECH_RESOURCE=${SPEECH_RESOURCE}
AZURE_SPEECH_REGION=${SPEECH_REGION}
SPEECH_ENDPOINT=${SPEECH_ENDPOINT}
EOF
chmod 600 "$ENV_FILE"
info ".env written to $ENV_FILE (chmod 600)"

info "Deployment complete."
info "  Resource : $SPEECH_RESOURCE"
info "  Region   : $SPEECH_REGION"
info "  Endpoint : $SPEECH_ENDPOINT"
info ""
info "To authenticate without a key:"
info "  az login                      # interactive"
info "  export AZURE_TENANT_ID=...    # or workload identity"
info "Keys (if enableLocalAuth=true):"
info "  az cognitiveservices account keys list -n $SPEECH_RESOURCE -g $RG --query key1 -o tsv > key.txt"
info "  chmod 600 key.txt"
