"""Evaluate the trained MONAI U-Net on the held-out **test** split.

Data source (in priority order):
  1. NPZ files in --data-dir/test/  (generated by generate_data.py --mode splits)
  2. In-memory generation with seed = <train_seed + 20_000> (default fallback)

Usage:
    # After training:
    python src/evaluate.py \
        --checkpoint data/checkpoints/best_model.pth \
        --data-dir data/ \
        --task grains --image-size 128 --seed 42 \
        --output data/
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path


# ── Argument validators ────────────────────────────────────────────────────


def _positive_int(value: str) -> int:
    try:
        v = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(f"expected integer, got {value!r}")
    if v <= 0:
        raise argparse.ArgumentTypeError(f"must be a positive integer (got {v})")
    return v


# ── NPZ dataset ────────────────────────────────────────────────────────────


class NPZSegDataset:
    """Load image/label pairs from NPZ files with validation.

    Uses context-manager-safe ``np.load`` to avoid file-handle leaks.
    """

    def __init__(self, npz_dir: Path) -> None:
        self.paths = sorted(npz_dir.glob("*.npz"))
        if not self.paths:
            raise FileNotFoundError(f"No .npz files found in {npz_dir}")

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int):
        import numpy as np

        path = self.paths[idx]
        with np.load(str(path), allow_pickle=False) as d:
            required = {"image", "label"}
            missing = required - set(d.keys())
            if missing:
                raise ValueError(
                    f"{path.name}: missing keys {missing}. "
                    f"Found: {list(d.keys())}"
                )
            image = d["image"].copy()
            label = d["label"].copy()

        # Validate
        if image.shape != label.shape:
            raise ValueError(
                f"{path.name}: image shape {image.shape} != label shape {label.shape}"
            )
        if image.dtype != np.float32:
            raise ValueError(f"{path.name}: image must be float32, got {image.dtype}")
        if label.dtype != np.float32:
            raise ValueError(f"{path.name}: label must be float32, got {label.dtype}")
        if not np.isfinite(image).all():
            raise ValueError(f"{path.name}: image contains NaN/Inf")
        if not np.isfinite(label).all():
            raise ValueError(f"{path.name}: label contains NaN/Inf")
        if image.min() < 0.0 or image.max() > 1.0:
            raise ValueError(
                f"{path.name}: image out of [0,1] range "
                f"[{image.min():.4f}, {image.max():.4f}]"
            )
        return image, label


# ── CLI ────────────────────────────────────────────────────────────────────


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--checkpoint", type=Path, required=True,
                   help="Path to best_model.pth from training")
    p.add_argument("--task", default="grains", choices=["grains", "particles"])
    p.add_argument("--image-size", type=_positive_int, default=128)
    p.add_argument(
        "--data-dir", type=Path, default=Path("data"),
        help="Directory with test/ subdirectory or fallback in-memory generation",
    )
    p.add_argument("--n-test", type=_positive_int, default=50,
                   help="Samples to generate if test/ NPZ dir not found")
    p.add_argument(
        "--seed", type=int, default=42,
        help="Train seed — test uses seed+20000 for in-memory fallback",
    )
    p.add_argument("--batch-size", type=_positive_int, default=8)
    p.add_argument("--device", default="cpu", choices=["cpu", "cuda"])
    p.add_argument("--output", type=Path, default=Path("data"))
    return p.parse_args()


# ── Main ───────────────────────────────────────────────────────────────────


def main() -> int:
    args = parse_args()

    import numpy as np
    import torch
    import monai
    from monai.data import DataLoader
    from monai.metrics import DiceMetric
    from torchmetrics.functional.classification import binary_jaccard_index

    sys.path.insert(0, str(Path(__file__).parent))
    from model import build_model

    if args.device == "cuda" and not torch.cuda.is_available():
        raise SystemExit("ERROR: --device cuda but CUDA is not available.")

    device = torch.device(args.device)
    pred_dir = args.output / "predictions"
    pred_dir.mkdir(parents=True, exist_ok=True)

    # ── Load checkpoint ────────────────────────────────────────────────────
    if not args.checkpoint.exists():
        raise SystemExit(f"ERROR: checkpoint not found: {args.checkpoint}")

    ckpt_sha256 = hashlib.sha256(args.checkpoint.read_bytes()).hexdigest()
    print(f"[eval] checkpoint: {args.checkpoint}")
    print(f"[eval] SHA-256: {ckpt_sha256}")

    model = build_model(in_channels=1, out_channels=1).to(device)
    model.load_state_dict(
        torch.load(args.checkpoint, weights_only=True, map_location=device)
    )
    model.eval()

    # ── Load test data ─────────────────────────────────────────────────────
    test_dir = args.data_dir / "test"
    if test_dir.exists() and any(test_dir.glob("*.npz")):
        print(f"[eval] loading test split from {test_dir}")
        ds = NPZSegDataset(test_dir)
        images = np.stack([ds[i][0] for i in range(len(ds))])
        labels = np.stack([ds[i][1] for i in range(len(ds))])
        n_test = len(ds)
    else:
        print(
            f"[eval] {test_dir} not found — generating {args.n_test} in-memory "
            f"test samples (seed={args.seed + 20_000})"
        )
        sys.path.insert(0, str(Path(__file__).parent))
        from generate_data import generate_batch
        images, labels = generate_batch(
            args.task, args.n_test, args.image_size, seed=args.seed + 20_000
        )
        n_test = args.n_test

    print(f"[eval] {n_test} test samples, image shape: {images.shape}")

    # ── Build MONAI-style list dataset ────────────────────────────────────
    import torch
    from monai.transforms import Compose, EnsureTyped

    val_transforms = Compose([
        EnsureTyped(keys=["image", "label"], dtype=torch.float32, track_meta=False),
    ])
    data_list = [
        {"image": images[i], "label": labels[i]} for i in range(n_test)
    ]
    from monai.data import CacheDataset
    test_ds = CacheDataset(
        data=data_list, transform=val_transforms, cache_rate=1.0, num_workers=0
    )
    test_loader = DataLoader(
        test_ds, batch_size=args.batch_size, shuffle=False, num_workers=0
    )

    # ── Inference ─────────────────────────────────────────────────────────
    dice_metric = DiceMetric(
        include_background=True, reduction="mean", get_not_nans=False
    )
    iou_sum = 0.0
    n_seen = 0
    per_image: list[dict] = []

    with torch.no_grad():
        for batch in test_loader:
            xb = batch["image"].to(device)
            yb = batch["label"].to(device)
            preds_bin = (torch.sigmoid(model(xb)) > 0.5).float()
            dice_metric(y_pred=preds_bin, y=yb)
            iou_sum += float(binary_jaccard_index(preds_bin.long(), yb.long())) * xb.size(0)
            n_seen += xb.size(0)

    test_dice = float(dice_metric.aggregate())
    test_iou = iou_sum / max(1, n_seen)
    dice_metric.reset()

    if not math.isfinite(test_dice) or not math.isfinite(test_iou):
        raise SystemExit(
            f"ERROR: non-finite test metrics: dice={test_dice!r} iou={test_iou!r}"
        )

    print(f"[eval] Test Dice = {test_dice:.4f}  IoU = {test_iou:.4f}")

    # ── Per-image metrics ─────────────────────────────────────────────────
    all_x = torch.stack([test_ds[i]["image"] for i in range(n_test)])
    all_y = torch.stack([test_ds[i]["label"] for i in range(n_test)])
    with torch.no_grad():
        preds_all = torch.sigmoid(model(all_x.to(device))).cpu()
    preds_bin_all = (preds_all > 0.5).float()

    for i in range(n_test):
        dm = DiceMetric(include_background=True, reduction="mean", get_not_nans=False)
        dm(y_pred=preds_bin_all[i:i+1].float(), y=all_y[i:i+1].float())
        per_image.append({
            "index": i,
            "iou": float(binary_jaccard_index(
                preds_bin_all[i].long().unsqueeze(0),
                all_y[i].long().unsqueeze(0),
            )),
            "dice": float(dm.aggregate()),
        })

    results = {
        "checkpoint": str(args.checkpoint),
        "checkpoint_sha256": ckpt_sha256,
        "n_test": n_test,
        "test_dice": test_dice,
        "test_iou": test_iou,
        "monai_version": monai.__version__,
        "per_image": per_image,
    }
    out_path = pred_dir / "test_metrics.json"
    out_path.write_text(json.dumps(results, indent=2, allow_nan=False))
    print(f"[eval] wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
