#!/usr/bin/env bash
# infra/deploy.sh — deploy the Azure ML workspace stack for D-2 MACE-MP.
#
# Prerequisites checked at runtime:
#   - az CLI (>= 2.60) and az bicep installed
#   - AzureML + ContainerRegistry + Storage + KeyVault + OperationalInsights providers registered
#   - AML compute quota (queried via `az ml compute list-usage` after workspace exists)
#   - Signed-in user's object ID discoverable
#
# The script generates ../.env from Bicep outputs so subsequent scripts and docs
# can `set -a && source .env && set +a` without hard-coding names.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SCENARIO_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-rg-spread-materials-02}"
AZURE_LOCATION="${AZURE_LOCATION:-japaneast}"
NAME_PREFIX="${NAME_PREFIX:-macemp02}"

command -v az >/dev/null || { echo "ERROR: az CLI not found." >&2; exit 1; }

echo "[preflight] resource providers ..."
for rp in Microsoft.MachineLearningServices Microsoft.ContainerRegistry \
          Microsoft.Storage Microsoft.KeyVault Microsoft.OperationalInsights \
          Microsoft.Compute; do
  state=$(az provider show -n "$rp" --query registrationState -o tsv 2>/dev/null || echo "NotRegistered")
  if [ "$state" != "Registered" ]; then
    echo "[preflight] registering $rp (was: $state) ..."
    az provider register -n "$rp" --wait
  fi
done

PRINCIPAL_ID="$(az ad signed-in-user show --query id -o tsv 2>/dev/null || true)"
if [ -z "$PRINCIPAL_ID" ]; then
  echo "ERROR: could not resolve signed-in user's object id. Run 'az login' first." >&2
  exit 1
fi

echo "[preflight] resource group $AZURE_RESOURCE_GROUP in $AZURE_LOCATION ..."
az group show -n "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1 || \
  az group create -n "$AZURE_RESOURCE_GROUP" -l "$AZURE_LOCATION" >/dev/null

DEPLOYMENT_NAME="macemp02-$(date -u +%Y%m%d-%H%M%S)"
echo "[deploy] running Bicep deployment $DEPLOYMENT_NAME ..."
az deployment group create \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters "@$SCRIPT_DIR/parameters.example.json" \
    principalId="$PRINCIPAL_ID" \
    namePrefix="$NAME_PREFIX" \
  --output none

outputs_json=$(az deployment group show \
  --resource-group "$AZURE_RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --query properties.outputs -o json)

get() { echo "$outputs_json" | python3 -c "import json,sys; print(json.load(sys.stdin)['$1']['value'])"; }

WS_NAME=$(get workspaceName)
KV_NAME=$(get keyVaultName)
STORAGE=$(get storageAccountName)
ACR_NAME=$(get acrName)
LOC=$(get location)

echo "[preflight] AML compute quota in $LOC ..."
az ml compute list-usage -g "$AZURE_RESOURCE_GROUP" -w "$WS_NAME" -l "$LOC" -o table || \
  echo "[preflight] WARNING: 'az ml compute list-usage' failed — install ml extension: az extension add -n ml"

ENV_FILE="$SCENARIO_DIR/.env"
echo "[deploy] writing $ENV_FILE"
cat >"$ENV_FILE" <<EOF
# Generated by infra/deploy.sh at $(date -u +%FT%TZ)
AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
AZURE_LOCATION=$LOC
AML_WORKSPACE_NAME=$WS_NAME
AML_KEY_VAULT_NAME=$KV_NAME
AML_STORAGE_ACCOUNT=$STORAGE
AML_CONTAINER_REGISTRY=$ACR_NAME
EOF
chmod 600 "$ENV_FILE"

cat <<EOF

✅ Deployment complete.
   AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
   AML_WORKSPACE_NAME=$WS_NAME
   AML_KEY_VAULT_NAME=$KV_NAME
   AML_STORAGE_ACCOUNT=$STORAGE

Next: set -a && source $ENV_FILE && set +a
      Then follow docs/03-aml-gpu.md.
EOF
